"""add jobs retry_count and last_error columns

Revision ID: 033023b7198f
Revises: 35148b2c0ced
Create Date: 2026-07-04 09:30:41.759987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "033023b7198f"
down_revision: Union[str, Sequence[str], None] = "35148b2c0ced"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("jobs", sa.Column("last_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "last_error")
    op.drop_column("jobs", "retry_count")
    # ### end Alembic commands ###
