"""add jobs status_created_at index

Revision ID: 35148b2c0ced
Revises: e65dfb4b5b26
Create Date: 2026-07-04 08:51:55.533004

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35148b2c0ced"
down_revision: Union[str, Sequence[str], None] = "e65dfb4b5b26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_jobs_status_created_at", "jobs", ["status", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_jobs_status_created_at", table_name="jobs")
    # ### end Alembic commands ###
